### ISSUE TITLE
[feature request] Parameter to set number of upcoming rides instead of X minutes into the future

### ISSUE THREAD

**Issue by istvnurbn** [amaximus/bkk_stop#19]
Hi,

This falls into the same category as the [issue](https://github.com/amaximus/bkk-stop-card/issues/8) I opened for the bkk-stop-card.

Is it possible to look for the next X number of rides from the same stop instead of all the rides within Y amount of minutes?

Thanks!

**Comment by amaximus** [comment]
Hi,

since the rides are stored as attributes, there is no point in limiting their number, except for avoiding too many items in the list.

The frontend side, e.g. displaying information, can however limit the number of items to show, either by the bkk-stop-card's new parameter or by any other solution to display information (different users use different solutions).
All relevant information is in the attributes of the sensor, frontend logic should iterate over them and limit their number, if needed.

**Comment by istvnurbn** [comment]
Hi!

I get your point, however, I think you can already limit the number of attributes with the minsAfter option. Limiting them by amount is just adds flexibility.

In case you want to show data not using your (actually pretty good) card then you'll need to do html or other trickery. While adding the limit by amount option tackles the issue from the get-go.

**Comment by amaximus** [comment]
Hi,

recentrly published version 2.2.0 adds support for maximum number of items to consider.

Please update the integration and come back to me with results.

**Comment by istvnurbn** [comment]
Hi,

The card itself only shows the next 2 rides instead of the next 4 (or any other number for that matter) with the following parameters:

**Sensor:**

```yaml
sensor:
  - platform: bkk_stop
    name: "bkk_fay_to_downtown_tram"
    stopId: "BKK_F02674"
    maxItems: 4
```

**Card:**

```yaml
type: custom:bkk-stop-card
entity: sensor.bkk_fay_to_downtown_tram
name: Villamos
hide_in_mins: true
```

Does it interfere with the `ignoreNow` option in some way?
